# This is a working example.
# For a more complete reference use `--example`
kibot:
  version: 1

global:
  filters:
  - number: 1007
  - number: 1015
  - number: 58
  out_dir: Output

filters:
- name: only_jlc_parts
  comment: Only parts with JLC (LCSC) code
  type: generic
  include_only:
  - column: LCS
    regex: ^C\d+

variants:
- name: place_holder
  comment: Just a place holder for pre_transform filters
  type: kicost
  pre_transform:
  - _kicost_rename
  - _rot_footprint

outputs:
- name: basic_boardview
  comment: Board View export
  type: boardview
  dir: Assembly
- name: basic_download_datasheets
  comment: Download the datasheets
  type: download_datasheets
  dir: Datasheets
- name: PCBWay_gerbers
  comment: Gerbers compatible with PCBWay
  type: gerber
  dir: Manufacturers/PCBWay
  options:
    exclude_edge_layer: true
    exclude_pads_from_silkscreen: true
    plot_sheet_reference: false
    plot_footprint_refs: true
    plot_footprint_values: true
    force_plot_invisible_refs_vals: false
    tent_vias: true
    use_protel_extensions: true
    create_gerber_job_file: false
    output: '%f.%x'
    gerber_precision: 4.6
    use_gerber_x2_attributes: false
    use_gerber_net_attributes: false
    disable_aperture_macros: true
    line_width: 0.1
    subtract_mask_from_silk: false
    inner_extension_pattern: .gl%N
  layers: &id002
  - layer: F.Cu
    suffix: F_Cu
    description: Front copper
  - layer: In1.Cu
    suffix: In1_Cu
    description: Inner layer 1
  - layer: In2.Cu
    suffix: In2_Cu
    description: Inner layer 2
  - layer: B.Cu
    suffix: B_Cu
    description: Bottom copper
  - layer: F.Paste
    suffix: F_Paste
    description: Front solder paste
  - layer: B.Silkscreen
    suffix: B_Silkscreen
    description: Bottom silkscreen (artwork)
  - layer: F.Silkscreen
    suffix: F_Silkscreen
    description: Front silkscreen (artwork)
  - layer: B.Mask
    suffix: B_Mask
    description: Bottom soldermask (negative)
  - layer: F.Mask
    suffix: F_Mask
    description: Front soldermask (negative)
  - layer: Edge.Cuts
    suffix: Edge_Cuts
    description: Board shape
- name: PCBWay_drill
  comment: Drill files compatible with PCBWay
  type: excellon
  dir: Manufacturers/PCBWay
  options:
    metric_units: false
    minimal_header: true
    zeros_format: SUPPRESS_LEADING
    left_digits: 2
    right_digits: 4
    pth_and_npth_single_file: false
    pth_id: ''
    npth_id: -NPTH
    output: '%f%i.drl'
- name: PCBWay
  comment: ZIP file for PCBWay
  type: compress
  dir: Manufacturers
  options:
    format: ZIP
    files:
    - from_output: PCBWay_gerbers
      dest: /
    - from_output: PCBWay_drill
      dest: /
- name: JLCPCB_gerbers
  comment: Gerbers compatible with JLCPCB
  type: gerber
  dir: Manufacturers/JLCPCB
  options:
    exclude_edge_layer: true
    exclude_pads_from_silkscreen: true
    plot_sheet_reference: false
    plot_footprint_refs: true
    plot_footprint_values: false
    force_plot_invisible_refs_vals: false
    tent_vias: true
    use_protel_extensions: true
    create_gerber_job_file: false
    disable_aperture_macros: true
    gerber_precision: 4.6
    use_gerber_x2_attributes: false
    use_gerber_net_attributes: false
    line_width: 0.1
    subtract_mask_from_silk: true
    inner_extension_pattern: .g%n
  layers: *id002
- name: JLCPCB_drill
  comment: Drill files compatible with JLCPCB
  type: excellon
  dir: Manufacturers/JLCPCB
  options:
    pth_and_npth_single_file: false
    pth_id: -PTH
    npth_id: -NPTH
    metric_units: true
    map: gerber
    route_mode_for_oval_holes: false
    output: '%f%i.%x'
- name: JLCPCB_position
  comment: Pick and place file, JLCPCB style
  type: position
  dir: Manufacturers/JLCPCB
  options:
    variant: place_holder
    output: '%f_cpl_jlc.%x'
    format: CSV
    units: millimeters
    separate_files_for_front_and_back: false
    only_smd: true
    columns:
    - id: Ref
      name: Designator
    - Val
    - Package
    - id: PosX
      name: Mid X
    - id: PosY
      name: Mid Y
    - id: Rot
      name: Rotation
    - id: Side
      name: Layer
- name: JLCPCB_bom
  comment: BoM for JLCPCB
  type: bom
  dir: Manufacturers/JLCPCB
  options:
    output: '%f_%i_jlc.%x'
    exclude_filter: only_jlc_parts
    ref_separator: ','
    columns:
    - field: Value
      name: Comment
    - field: References
      name: Designator
    - Footprint
    - field: LCSC
      name: 'LCSC Part #'
    csv:
      hide_pcb_info: true
      hide_stats_info: true
      quote_all: true
- name: JLCPCB
  comment: ZIP file for JLCPCB
  type: compress
  dir: Manufacturers
  options:
    files:
    - from_output: JLCPCB_gerbers
      dest: /
    - from_output: JLCPCB_drill
      dest: /
    - from_output: JLCPCB_position
      dest: /
    - from_output: JLCPCB_bom
      dest: /
- name: basic_ibom
  comment: Interactive HTML BoM
  type: ibom
  dir: Assembly
- name: basic_info
  comment: Information about the run
  type: info
  dir: .
- name: basic_pcb_print_pdf
  comment: PCB
  type: pcb_print
  dir: PCB/PDF
  options:
    format: PDF
    pages:
    - layers:
      - layer: F.Cu
      - layer: F.Mask
        color: '#14332440'
      - layer: F.Paste
      - layer: F.Silkscreen
      - layer: Edge.Cuts
      sheet: Front copper
    - layers:
      - layer: In1.Cu
      - layer: Edge.Cuts
      sheet: Inner layer 1
    - layers:
      - layer: In2.Cu
      - layer: Edge.Cuts
      sheet: Inner layer 2
    - layers:
      - layer: B.Cu
      - layer: B.Mask
        color: '#14332440'
      - layer: B.Silkscreen
      - layer: Edge.Cuts
      mirror: true
      sheet: Bottom copper
    - layers:
      - layer: F.Courtyard
      - layer: Edge.Cuts
      sheet: Front courtyard area
    - layers:
      - layer: F.Fab
      - layer: Edge.Cuts
      sheet: Front documentation
    keep_temporal_files: false
    plot_sheet_reference: false
    scaling: 6.0
- name: basic_pcbdraw_svg_jlcpcb_green_enig_top
  comment: PCB 2D render in SVG format, using jlcpcb-green-enig style
  type: pcbdraw
  dir: PCB/2D_render/jlcpcb_green_enig
  options:
    style: jlcpcb-green-enig
    format: svg
- name: basic_pdf_sch_print
  comment: Schematic in PDF format
  type: pdf_sch_print
  dir: Schematic
- name: basic_render_3d_top
  comment: 3D view from top
  type: render_3d
  dir: 3D
  options:
    ray_tracing: true
    orthographic: true
- name: basic_render_3d_30deg
  comment: 3D view from 30 degrees
  type: render_3d
  dir: 3D
  output_id: 30deg
  options:
    ray_tracing: true
    rotate_x: 3
    rotate_z: -2
- name: basic_render_3d_bottom
  comment: 3D view from bottom
  type: render_3d
  dir: 3D
  options:
    ray_tracing: true
    orthographic: true
    view: bottom
- name: report_simple
  comment: Simple design report
  type: report
  output_id: _simple
  options:
    template: simple_ASCII
- name: report_full
  comment: Full design report
  type: report
  options:
    template: full_SVG
